### ISSUE TITLE
get branch monitor working (some basic example)

### ISSUE THREAD

**Issue by ejrgilbert** [ejrgilbert/whamm#10]

**Comment by wavid-b** [comment]
![Screen Shot 2024-06-10 at 12 07 58 PM](https://github.com/ejrgilbert/whamm/assets/102263445/ff89375b-6865-4a6f-ab65-01f29f113ba3)
![Screen Shot 2024-06-10 at 12 08 43 PM](https://github.com/ejrgilbert/whamm/assets/102263445/aa42c02e-03b2-4208-b7a8-01e1cdfcdc75)
Screenshots for what initialization output is. It adds many local.set commands and i32s. 
Also, assignment does nothing to the WASM

**Comment by wavid-b** [comment]
Here is full list of tested emitted code (where it compiles right)
https://docs.google.com/document/d/15rWriM1MgrqZFpzqWdbI5SPWiLiOHN9c3zO5HmiNWNU/edit?usp=sharing
