### ISSUE TITLE
Potential bug for getting function names

### ISSUE THREAD

**Issue by ahuoguo** [ejrgilbert/whamm#109]
Here I assumed all imports are functions, which is a wrong assumption. It doesn't break anything now since all of are test cases only have functions

https://github.com/ejrgilbert/whamm/blob/master/src/emitter/rewriting/rules/wasm.rs#L164

- [x] write a `wast` test for importing data, and instrumenting with `target_fn_name`
- [x] correct the behavior

**Comment by ejrgilbert** [comment]
I'm working on this with the "fleshing out of event stuff," already on my todo list.
