### ISSUE TITLE
Issues with reporting-vars

### ISSUE THREAD

**Issue by wavid-b** [ejrgilbert/whamm#130]
### Too many strings in data section cause table out-of-bounds
To get the buggy version, uncomment the code for calling "generator/instr_generator::after_run" and inside "emitter/rewriting::print_report_all"
The most complex version that runs correctly is: 
![Screen Shot 2024-08-01 at 4 59 39 PM](https://github.com/user-attachments/assets/8397a608-bbe0-44f2-99c9-add61b2b195e)
![Screen Shot 2024-08-01 at 4 59 46 PM](https://github.com/user-attachments/assets/490c5c69-03a4-46c1-93f8-02ecfde88911)
- Not all strings for metadata are in memory
- Some insert_i32_strings were removed (for the strings that were manually removed from memory)
- If the strings are all in memory, and the functions for using them are removed, it breaks --> the issue is with having these strings in memory

### print_meta's "expect" fails 
![Screen Shot 2024-08-02 at 10 27 05 AM](https://github.com/user-attachments/assets/66e5fb8c-6946-49ad-b63d-7062f2430204)
- even when maps it accesses are explicitly made ahead of call

**Comment by wavid-b** [comment]
Realized a problem: The print_meta tries to get all maps in the code, even those that have yet to be created. 
Solution: change the way print maps behaves if it fails to get the map out of "MY_MAPS"

**Comment by wavid-b** [comment]
Another thing with the strings - the size matters not the number of data segments:
`  (data (;4;) (i32.const 1052587) "whatever\09 0\09 \09 a\09 script0\09 (94, 14)\09 wasm_opcode_call_before8c\09 script0\09 (94, 14)\09 wasm_opcode_call_before8c\09 script0\09 (96, 14)\09 wasm_opcode_call_before5a\09 script0\09 (96, 14)\09 wasm_opcode_call_before5")
` still bugs

**Comment by ejrgilbert** [comment]
String bug:
- [ ] See if multi-memory is supported in our testing environments. If so, use that.
- [ ] Try shipping the map library as another module to import from.

**Comment by ejrgilbert** [comment]
Actually this was because the `print_meta` function assumed that variables would be in the map...but they are globals so they're not going to exist there! I now have a `print_global_meta` and `print_map_meta` that distinguish this case.
