### ISSUE TITLE
Can `wasmparser` be a better long-term library for bytecode rewriting?

### ISSUE THREAD

**Issue by ejrgilbert** [ejrgilbert/whamm#42]
`walrus` is basically an abandoned project, `wasmparser` could be a better approach to migrate to using, especially as new versions of Wasm come out with new features that may have events we want to instrument with this injection technique.

**Comment by ejrgilbert** [comment]
Used by Dfinity [here](https://github.com/dfinity/ic/blob/afafd1a63165a1f3865df264d000f6fc2423d944/rs/embedders/src/wasm_utils/instrumentation.rs#L912)

**Comment by ahuoguo** [comment]
1. wasm bytecode location identifier?
2. lib-agnostic IDs
3. Can wasmparser **create** a wasm module from scratch?

**Comment by ahuoguo** [comment]
Seems like we also want to use `wasm-encoder`

**Comment by thesuhas** [comment]
[Orca](https://github.com/thesuhas/orca) is able to inject code! Although, there is still a lot of functionality to be added, it's able to inject code now!
