### ISSUE TITLE
Panic at parsing for integer values outside i32

### ISSUE THREAD

**Issue by ahuoguo** [ejrgilbert/whamm#51]
The script `wasm:bytecode:call:alt / (1 + 2147483648) / {  }` will cause pest panic. 

```
thread 'verifier::tests::test_type_error_pred_final' panicked at src/parser/whamm_parser.rs:724:52:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }
```
Issue exists just for the sake of documenting.

**Comment by ejrgilbert** [comment]
We could catch this and make a better error though.

**Comment by wavid-b** [comment]
I forgot I fixed this in a PR forever ago
