### ISSUE TITLE
A better integration testing framework

### ISSUE THREAD

**Issue by ejrgilbert** [ejrgilbert/whamm#53]
We could have much better integration testing for probes. Here's an idea for the design.

Consider the probe specification `wasm:bytecode:br_if:before`, for a given Wasm program, the number of times this is injected _and_ the location it was injected in bytecode are deterministic.
Even the emitted code at that specific location is deterministic!

We could modify the `generator`/`emitter` to have a tracing mode that collects this information during instrumentation to enable an integration test to make assertions on the tracing data based on some trusted instrumentation execution!

I'm unsure what this would look like for making assertions on the actual code that is emitted, but since it's technically deterministic, I don't see why it would be impossible.

**Comment by thesuhas** [comment]
What kind of granularity would be good? We can build tracing into orca.

Currently what we do for tests is iterate through using the visitor and perform operations, reset the visitor and now iterate and perform assertions.

For tracing, some ideas I had were:
- Counter of number of injected instructions
- Store a reference to locations that have injections

**Comment by ahuoguo** [comment]
I think we can even have a `instr_at(loc: Location) -> Option<Operator>` that just grabs things directly. We can store location of interests from the iterator and do some calculations on the `Location` struct directly

**Comment by ejrgilbert** [comment]
I came up with a better idea for this!

Using `wast` files, we can write our test cases for how code should behave dynamically post-instrumentation. To do this, I can write some `bash` script to do this. Here's the idea:

```
(module
  (memory 1)
  (func $orig_target (param $arg0 i32) (result i32)
      local.get $arg0
  )
  (func (export "instrument_me") (param $i i32) (result i64)
    call $orig_target
  )
)

;; wasm:opcode:call:before { arg0 = 1; }
(assert_return (invoke "instrument_me" (i32.const 0)) (i32.const 1)) ;; fails without instrumentation
```

Note that the wast test would fail without instrumentation running successfully. The `bash` script would need to:
1. parse out the `module`, the `whamm` script (in the comment), and the test case
2. run `whamm` on the `module` with the script
3. re-stitch the `wast` file together
4. run the `wast` file on the target VM (`wasmtime` for now)
