### ISSUE TITLE
Print Visitor Indentation in Blocks

### ISSUE THREAD

**Issue by wavid-b** [ejrgilbert/whamm#55]
The indentation is kinda weird on print visitor when visiting blocks. IMO not worth spending the time on rn. SS attached of example:
![Screen Shot 2024-06-12 at 2 16 26 PM](https://github.com/ejrgilbert/whamm/assets/102263445/c980b24a-ca8d-48c2-911d-b6169a245300)

**Comment by ahuoguo** [comment]
Fixed in #49
