### ISSUE TITLE
Cannot call strcmp in User-def functions, probes, or global space

### ISSUE THREAD

**Issue by wavid-b** [ejrgilbert/whamm#57]
![error - strcmp in userspace](https://github.com/ejrgilbert/whamm/assets/102263445/6bb38117-c792-485d-99f4-524d6a99fbca)

**Comment by wavid-b** [comment]
can add screenshots of the other bugged cases if you need

**Comment by ahuoguo** [comment]
I think the problem is we are not treating function calls as statements.

The following script parses correctly: 
```DTrace
    BEGIN { a = strcmp((arg0, arg1), "bookings"); }
```

**Comment by wavid-b** [comment]
user-defined fn calls are being parsed as statements though, thats why I don't get it being different for strcmp. 
I'll check some more edge cases though

**Comment by wavid-b** [comment]
``` a = strcmp((arg0, arg1), "bookings"); ``` 
is working correctly in all 3 spaces, but not without the "a"
