### ISSUE TITLE
add language capabilities

### ISSUE THREAD

**Issue by ejrgilbert** [ejrgilbert/whamm#9]
- [x] call instr.wasm funcs
- [x] top of stack var (`tos`)
- [x] `arg*` for typed bytecodes (e.g. br_if, and, etc.)
- [x] `pc` (index in the function)
- [x] Create "fat" `instr.wasm` written in Rust (counting, tracking of data (assoc arrays), output to CSV, fault injection?)
- [ ] Import capability `import instr-core.wasm as core`
- [ ] Calls to imported wasm files:`core.foo(x, y, z)`
- [x] Add merge capability to CLI

**Comment by ahuoguo** [comment]
For 8 (Add merge capability to CLI), there might be some `wasm-tools` feature to do that?
